In [55]:
import pandas as pd 
import numpy as np 
import matplotlib as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder

In [2]:
!pip install sklearn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1310 sha256=4d2d63762b6a58e0a2d87a0de1b2bdca9bbf52b6ceb43b40ce83b593456e240f
  Stored in directory: /root/.cache/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn


In [7]:
train = pd.read_csv('/content/train.csv')
test = pd.read_csv('/content/test.csv')

In [8]:
train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [9]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [10]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [12]:
train.groupby("Sex").mean()

PassengerId  Survived    Pclass        Age     SibSp     Parch  \
Sex                                                                      
female   431.028662  0.742038  2.159236  27.915709  0.694268  0.649682   
male     454.147314  0.188908  2.389948  30.726645  0.429809  0.235702   

             Fare  
Sex                
female  44.479818  
male    25.523893

In [13]:
train.groupby("Cabin").mean()

PassengerId  Survived  Pclass    Age  SibSp  Parch       Fare
Cabin                                                               
A10          584.0       0.0     1.0  36.00    0.0   0.00  40.125000
A14          476.0       0.0     1.0    NaN    0.0   0.00  52.000000
A16          557.0       1.0     1.0  48.00    1.0   0.00  39.600000
A19          285.0       0.0     1.0    NaN    0.0   0.00  26.000000
A20          600.0       1.0     1.0  49.00    1.0   0.00  56.929200
...            ...       ...     ...    ...    ...    ...        ...
F33          310.0       1.0     2.0  29.00    0.0   0.00  11.333333
F38          777.0       0.0     3.0    NaN    0.0   0.00   7.750000
F4           401.5       1.0     2.0   2.50    2.0   1.00  39.000000
G6           216.0       0.5     3.0  14.75    0.5   1.25  13.581250
T            340.0       0.0     1.0  45.00    0.0   0.00  35.500000

[147 rows x 7 columns]

In [14]:
train['Sex'].unique()

array(['male', 'female'], dtype=object)

In [15]:
train.groupby("Embarked").mean()

PassengerId  Survived    Pclass        Age     SibSp     Parch  \
Embarked                                                                   
C          445.357143  0.553571  1.886905  30.814769  0.386905  0.363095   
Q          417.896104  0.389610  2.909091  28.089286  0.428571  0.168831   
S          449.527950  0.336957  2.350932  29.445397  0.571429  0.413043   

               Fare  
Embarked             
C         59.954144  
Q         13.276030  
S         27.079812

In [16]:
le = LabelEncoder()

In [17]:
train['Embarked']

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [18]:
train['Embarked'] = le.fit_transform(train['Embarked'])
train['Sex'] = le.fit_transform(train['Embarked'])

In [19]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    2  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    0  38.0      1      0   
2                             Heikkinen, Miss. Laina    2  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    2  35.0      1      0   
4                           Allen, Mr. William Henry    2  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2

In [20]:
train['Sex'].unique()

array([2, 0, 1, 3])

In [21]:
train['Embarked'].unique()

array([2, 0, 1, 3])

In [22]:
train = train.drop(['Cabin', 'Ticket', 'PassengerId', 'Name'], axis='columns')

In [23]:
train.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    2  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    2  26.0      0      0   7.9250         2
3         1       1    2  35.0      1      0  53.1000         2
4         0       3    2  35.0      0      0   8.0500         2

In [24]:
train.groupby('Parch').mean()

Survived    Pclass       Sex        Age     SibSp       Fare  Embarked
Parch                                                                        
0      0.343658  2.321534  1.538348  32.178503  0.237463  25.586774  1.538348
1      0.550847  2.203390  1.440678  24.422000  1.084746  46.778180  1.440678
2      0.500000  2.275000  1.637500  17.216912  2.062500  64.337604  1.637500
3      0.600000  2.600000  1.600000  33.200000  1.000000  25.951660  1.600000
4      0.000000  2.500000  2.000000  44.500000  0.750000  84.968750  2.000000
5      0.200000  3.000000  1.800000  39.200000  0.600000  32.550000  1.800000
6      0.000000  3.000000  2.000000  43.000000  1.000000  46.900000  2.000000

In [25]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  891 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 55.8 KB


In [41]:
train = train.dropna()

In [42]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  714 non-null    int64  
 1   Pclass    714 non-null    int64  
 2   Sex       714 non-null    int64  
 3   Age       714 non-null    float64
 4   SibSp     714 non-null    int64  
 5   Parch     714 non-null    int64  
 6   Fare      714 non-null    float64
 7   Embarked  714 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 50.2 KB


In [43]:
x_train = train['Survived']

In [46]:
train['Age'] = train['Age'].astype(int)
train['Fare'] = train['Fare'].astype(int)

In [47]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  714 non-null    int64
 1   Pclass    714 non-null    int64
 2   Sex       714 non-null    int64
 3   Age       714 non-null    int64
 4   SibSp     714 non-null    int64
 5   Parch     714 non-null    int64
 6   Fare      714 non-null    int64
 7   Embarked  714 non-null    int64
dtypes: int64(8)
memory usage: 50.2 KB


In [48]:
y_train = train[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']]

In [49]:
model = LinearRegression()

In [68]:
model.fit(y_train, x_train)

LinearRegression()

In [52]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [54]:
test['Embarked'] = le.fit_transform(test['Embarked'])
test['Sex'] = le.fit_transform(test['Embarked'])

In [58]:
test = test.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis = 1)

In [62]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    418 non-null    int64  
 1   Sex       418 non-null    int64  
 2   Age       332 non-null    float64
 3   SibSp     418 non-null    int64  
 4   Parch     418 non-null    int64  
 5   Fare      417 non-null    float64
 6   Embarked  418 non-null    int64  
dtypes: float64(2), int64(5)
memory usage: 23.0 KB


In [63]:
test = test.dropna()

In [64]:
test['Age'] = test['Age'].astype(int)
test['Fare'] = test['Fare'].astype(int)

In [69]:
preds = model.predict(test)

In [70]:
preds

array([ 0.2103236 ,  0.00125671,  0.21383285,  0.2248444 ,  0.26421465,
        0.33443426,  0.24391853,  0.47538864,  0.38937998,  0.1713249 ,
        0.5483048 ,  0.70902425,  0.1124586 ,  0.49892144,  0.52976883,
        0.44181764,  0.36418379,  0.16923135,  0.16261422,  0.52027223,
        0.42494777,  0.91280643,  0.81442514, -0.02109507,  0.9044077 ,
        0.35578506,  0.59192384,  0.22164212,  0.38683417,  0.22603728,
        0.72942784,  0.38937998,  0.27523679,  0.24204821,  0.2664026 ,
        0.10685581,  0.43954098,  0.51206179,  0.24123552,  0.64727591,
        0.54039314,  0.25401606,  0.69168593,  0.5549032 ,  0.46813625,
        0.73208145,  0.25096385,  0.1572482 ,  0.24123552,  0.81754288,
        0.30842538,  0.42274351,  0.30002664,  0.31110839,  1.00221613,
        0.34470331,  0.54640759,  0.76445181,  0.67565127,  0.29431092,
        0.27483045,  0.20764059,  0.78924166,  0.80521801,  0.83041421,
        0.36189645,  0.43954098,  0.29431092,  0.48916674,  0.39